## Project
name: snowflake_dbt_projects
version: "1.0"
config-version: 2
profile: snowflake_dbt_projects

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  snowflake_dbt_projects:
    staging:
      +materialized: view
    marts:
      +materialized: table
